services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bootcamp
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - bootcamp-dados:/var/lib/postgresql/data

volumes:
  bootcamp-dados:
